AuthType=auth/munge
AuthAltTypes=auth/jwt
AuthAltParameters=jwt_key=/etc/slurm/jwt.key
DbdAddr=slurmdbd
DbdHost=slurmdbd
SlurmUser=slurm
DebugLevel=debug
LogFile=/var/log/slurm/slurmdbd.log
PidFile=/var/run/slurm/slurmdbd.pid
StorageType=accounting_storage/mysql
StorageHost=mysql
StorageUser=slurm
StoragePass=slurmpass
StorageLoc=slurm_acct_db
